# Generated by Django 4.2.7 on 2023-11-24 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_courses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'ordering': ('name',), 'verbose_name': 'course'},
        ),
        migrations.RemoveField(
            model_name='courses',
            name='created',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='updated',
        ),
        migrations.AlterField(
            model_name='courses',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='college.departments'),
        ),
    ]
