# Generated by Django 4.2.7 on 2023-11-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0006_materials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.TextField()),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('address', models.CharField(max_length=250, unique=True)),
                ('department', models.TextField()),
                ('course', models.TextField()),
                ('purpose', models.TextField()),
                ('materials', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'order',
                'ordering': ('name',),
            },
        ),
    ]
