# Generated by Django 4.2.7 on 2023-11-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0012_alter_order_address_alter_order_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='gender',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='purpose',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
