# Generated by Django 4.2.7 on 2023-11-25 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_alter_order_mobile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
